language: node_js
node_js:
  - "stable"

cache:
  npm: false

script:
  - npm i
  - npm run build

deploy:
  verbose: true
  provider: s3
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  bucket: "househunterfe" 
  region: "us-east-1"
  local_dir: dist
  skip_cleanup: true
  acl: public_read