export const sizes = [
  { text: '25m²', value: 25 },
  { text: '50m²', value: 50 },
  { text: '75m²', value: 75 },
  { text: '100m²', value: 110 },
  { text: '125m²', value: 125 },
  { text: '150m²', value: 150 },
];

export const prices = [
  { text: '€0', value: 0 },
  { text: '€500', value: 500 },
  { text: '€750', value: 750 },
  { text: '€1000', value: 1000 },
  { text: '€1250', value: 1250 },
  { text: '€1500', value: 1500 },
  { text: '€1750', value: 1750 },
  { text: '€2000', value: 2000 },
  { text: '€2500', value: 2500 },
  { text: '€3000', value: 3000 },
  { text: '€4000', value: 4000 },
  { text: '€5000', value: 5000 },
  { text: '€6000', value: 6000 },
];

export const bedrooms = [
  { text: '1 or more', value: 1 },
  { text: '2 or more', value: 2 },
  { text: '3 or more', value: 3 },
  { text: '4 or more', value: 4 },
  { text: '5 or more', value: 5 },
];

export const suburbs = [
  { text: '-- Select --', value: null},
  { text: 'Amstel III/Bullewijk' },
  { text: 'Apollobuurt' },
  { text: 'Banne Buiksloot' },
  { text: 'Bedrijventerrein Sloterdijk' },
  { text: 'Betondorp' },
  { text: 'Bijlmer Centrum (D,F,H)' },
  { text: 'Bijlmer Oost (E,G,K)' },
  { text: 'Buikslotermeer' },
  { text: 'Buitenveldert-Oost' },
  { text: 'Buitenveldert-West' },
  { text: 'Burgwallen-Nieuwe Zijde' },
  { text: 'Burgwallen-Oude Zijde' },
  { text: 'Centrale Markt' },
  { text: 'Chassébuurt' },
  { text: 'Da Costabuurt' },
  { text: 'Dapperbuurt' },
  { text: 'De Kolenkit' },
  { text: 'De Punt' },
  { text: 'De Weteringschans' },
  { text: 'Driemond' },
  { text: 'Eendracht' },
  { text: 'Elzenhagen' },
  { text: 'Erasmuspark' },
  { text: 'Frankendael' },
  { text: 'Frederik Hendrikbuurt' },
  { text: 'Gein' },
  { text: 'Geuzenbuurt' },
  { text: 'Geuzenveld' },
  { text: 'Grachtengordel-West' },
  { text: 'Grachtengordel-Zuid' },
  { text: 'Haarlemmerbuurt' },
  { text: 'Helmersbuurt' },
  { text: 'Holendrecht/Reigersbos' },
  { text: 'Hoofddorppleinbuurt' },
  { text: 'Hoofdweg e.o.' },
  { text: 'Houthavens' },
  { text: 'IJburg Oost' },
  { text: 'IJburg West' },
  { text: 'IJburg Zuid' },
  { text: 'IJplein/Vogelbuurt' },
  { text: 'IJselbuurt' },
  { text: 'Indische Buurt Oost' },
  { text: 'Indische Buurt West' },
  { text: 'Jordaan' },
  { text: 'Kadoelen' },
  { text: 'Kinkerbuurt' },
  { text: 'Landlust' },
  { text: 'Lutkemeer/Ookmeer' },
  { text: 'Middelveldsche Akerpolder' },
  { text: 'Middenmeer' },
  { text: 'Museumkwartier' },
  { text: 'Nellestein' },
  { text: 'Nieuwe Pijp' },
  { text: 'Nieuwendammerdijk/Buiksloterdijk' },
  { text: 'Nieuwmarkt/Lastage' },
  { text: 'Noordelijke IJ-oevers Oost' },
  { text: 'Noordelijke IJ-oevers West' },
  { text: 'Omval/Overamstel' },
  { text: 'Oostelijk Havengebied' },
  { text: 'Oostelijke Eilanden/Kadijken' },
  { text: 'Oosterparkbuurt' },
  { text: 'Oostzanerwerf' },
  { text: 'Osdorp-Midden' },
  { text: 'Osdorp-Oost' },
  { text: 'Oude Pijp' },
  { text: 'Overtoomse Sluis' },
  { text: 'Overtoomse Veld' },
  { text: 'Prinses Irenebuurt e.o.' },
  { text: 'Rijnbuurt' },
  { text: 'Scheldebuurt' },
  { text: 'Schinkelbuurt' },
  { text: 'Sloter-/Riekerpolder' },
  { text: 'Sloterdijk' },
  { text: 'Slotermeer-Noordoost' },
  { text: 'Slotermeer-Zuidwest' },
  { text: 'Slotervaart Noord' },
  { text: 'Slotervaart Zuid' },
  { text: 'Spaarndammer- en Zeeheldenbuurt' },
  { text: 'Staatsliedenbuurt' },
  { text: 'Stadionbuurt' },
  { text: 'Transvaalbuurt' },
  { text: 'Tuindorp Buiksloot' },
  { text: 'Tuindorp Nieuwendam' },
  { text: 'Tuindorp Oostzaan' },
  { text: 'Van Galenbuurt' },
  { text: 'Van Lennepbuurt' },
  { text: 'Volewijck' },
  { text: 'Vondelbuurt' },
  { text: 'Water' },
  { text: 'Waterland' },
  { text: 'Waterlandpleinbuurt' },
  { text: 'Weesperbuurt/Plantage' },
  { text: 'Weesperzijde' },
  { text: 'Westelijk Havengebied' },
  { text: 'Westindische Buurt' },
  { text: 'Westlandgracht' },
  { text: 'Willemspark' },
  { text: 'Zeeburgereiland/Nieuwe Diep' },
  { text: 'Zuid Pijp' },
  { text: 'Zuidas' },
];
